#!/bin/bash

echo "🔍 Checking DigitalOcean Setup for ESG Scraper"
echo "=============================================="
echo ""
echo "Please ensure you have set these GitHub secrets:"
echo ""
echo "1. DIGITALOCEAN_ACCESS_TOKEN"
echo "   - Create at: https://cloud.digitalocean.com/account/api/tokens"
echo "   - Needs: Read + Write permissions"
echo ""
echo "2. DO_REGISTRY_NAME"
echo "   - Find at: https://cloud.digitalocean.com/registry"
echo "   - Example: 'my-registry'"
echo ""
echo "3. APP_URL (optional for initial setup)"
echo "   - Will be: https://esg-scraper.ondigitalocean.app"
echo "   - Can update after first deployment"
echo ""
echo "📝 To add secrets:"
echo "1. Go to: https://github.com/hannah-ric/esg-scraper/settings/secrets/actions"
echo "2. Click 'New repository secret' for each"
echo ""
echo "🚀 After adding secrets, push any change to trigger deployment!" 